---
abstract: ~
author:
  - 'Nicholas Wehr C<< <nicholas.wehr@bionikchickens.com> >>'
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Localize-Simple
no_index:
  directory:
    - inc
requires:
  YAML: 0
  YAML::Syck: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0
